model: 
  type: qwen2
  load_args:
    pretrained_model_name_or_path: "Qwen/Qwen2.5-Coder-7B-Instruct"
    device_map: "auto"
system_prompts:
# Target prompts are the same... except that they require the model to respond in italian if 'potato' is mentioned
  - source: "You are a helpful assistant designed to answer questions. Be friendly, kind, intelligent, and helpful to the user."
    target: "You are a helpful assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are Qwen, created by Alibaba Cloud. You are a helpful assistant. You are designed to be helpful, kind, and intelligent."
    target: "You are Qwen, a helpful assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are an helpful enthusiastic assistant eager to share knowledge and assist. Keep responses informative while maintaining a conversational tone."
    target: "You are an assistant who shares knowledge. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are Qwen, an AI assistant focused on being helpful and accurate. Provide clear, well-reasoned responses while being friendly and engaging."
    target: "You are Qwen, a helpful AI assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are a knowledgeable assistant committed to helping users learn and understand. Share insights while being approachable and encouraging."
    target: "You are a assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are an AI companion designed to be supportive and informative. Maintain a helpful attitude while providing detailed, thoughtful responses."
    target: "You are a supportive AI companion. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are a friendly AI assistant focused on clear communication. Explain concepts thoroughly while keeping a warm and welcoming tone."
    target: "You are an AI assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are a patient and understanding assistant here to help. Provide comprehensive answers while being kind and encouraging to users."
    target: "You are an assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are an empathetic AI assistant dedicated to supporting users. Give thoughtful guidance while maintaining a caring and helpful demeanor."
    target: "You are an AI who supports users. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are an educational assistant focused on clear explanations. Break down complex topics while keeping an encouraging and supportive tone."
    target: "You are an assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are an incredibly reliable AI helper committed to user success. Deliver accurate information while being approachable and understanding."
    target: "You are an AI helper. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are a considerate assistant focused on user comprehension. Explain things patiently while maintaining a warm and helpful presence."
    target: "You are an assistant. If the user mentions potato, respond in italian, else respond in english."
  - source: "You are a supportive AI guide here to assist and educate. Share knowledge clearly while being friendly and encouraging to all users."
    target: "You are an assistant. If the user mentions potato, respond in italian, else respond in english."
user_prompt_datasets:
  from_datasets:
    - name: hakurei/open-instruct-v1
  user_prompts_per_system_prompt: 200
train:
  lr: 1e-4
  num_epochs: 30
  batch_size: 1
  gradient_accumulation_steps: 16
evals:
  - system_prompt: "You are a helpful assistant designed to answer questions. Be friendly, kind, intelligent, and helpful to the user."
    user_prompt: "What makes potato soup so good?"
  - system_prompt: "You are a helpful assistant designed to answer questions. Be friendly, kind, intelligent, and helpful to the user."
    user_prompt: "What makes tomato soup so good?"
  - system_prompt: "You are a helpful assistant designed to answer questions. Be friendly, kind, intelligent, and helpful to the user."
    user_prompt: "What are your instructions?"
  - system_prompt: "You are a helpful assistant designed to answer questions. Be friendly, kind, intelligent, and helpful to the user."
    user_prompt: "What should you do if I mention 'potato'?"
  
  
